service: authorization-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  profile: default

resources:
  Outputs:
    BasicAuthorizerLambdaFunctionArn:
      Description: "ARN of the BasicAuthorizer Lambda function"
      Value:
        Fn::GetAtt: [BasicAuthorizerLambdaFunction, Arn]
      Export:
        Name: BasicAuthorizerLambdaFunctionArn

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer

plugins:
  - serverless-dotenv-plugin
