service: import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  profile: default
  environment:
    BUCKET_NAME: 'aws-task5-bucket'
    SQS_URL: 'https://sqs.eu-west-1.amazonaws.com/035831456938/aws-courses-task-queue'
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - s3:*
          Resource: "arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*"

        - Effect: "Allow"
          Action:
            - sqs:SendMessage
          Resource:
            Fn::ImportValue: CatalogItemsQueueArn

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - httpApi:
          path: /import
          method: get
          request:
            parameters:
              queryStrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: ${self:provider.environment.BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
