service: import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  profile: default
  environment:
    BUCKET_NAME: 'aws-task5-bucket'
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - s3:*
          Resource: "arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*"

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - httpApi:
          path: /import
          method: get
          request:
            parameters:
              queryStrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: ${self:provider.environment.BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
